### ISSUE TITLE
师傅好，我的CTFm界面可以有web题目建立成功的消息，但是无法访问题目

### ISSUE THREAD

**Issue by Drun1baby** [EkiXu/CTFm#3]

**Comment by EkiXu** [comment]
请检查：
1. 数据库中是否有题目
2. 用户是否有权限访问题目（题目处于隐藏状态，比赛未开始...）

又及，可以更具体的描述一下问题吗，比如问题复现步骤，前后端报错日志情况

**Comment by Drun1baby** [comment]
是 Web 类型的题目，用户有权限访问题目；使用的是 dynamic_container。相关的报错截图发到师傅的博客了

**Comment by EkiXu** [comment]
师傅发到哪里了，我这边没有看到，方便直接贴在issue中吗
如果是dynamic_container创建问题
请检查：

1.
```
docker container ls
```
返回的结果中中是否创建了相关题目容器，如果没有，容器网络配置是否正确，题目镜像是否存在

2.
```
/backend/script/frps.ini
/backend/script/frpc.ini
```
中端口映射的配置是否正常更新，如果没有，请检查frps和frpc的token是否一致，frpc和frps是否能互相访问

3.服务端防火墙是否放通相关题目端口

**Comment by Drun1baby** [comment]
1. 
```
docker container ls
```
![Snipaste_2022-05-23_08-49-37](https://user-images.githubusercontent.com/75228348/169724196-3aed2f39-6165-47fb-be04-c3653348a0db.png)

返回的结果中创建了相关题目容器

2.

/backend/script/frps.ini
/backend/script/frpc.ini

这里配置应该是没问题的；

```
frpc.ini

[common]
server_addr = 172.1.0.1
server_port = 6490
token = quoCh8ep
pool_count = 200
tls_enable = true


admin_addr = 172.1.0.3
admin_port = 7400


<!------------>

frps.ini

[common]
bind_port = 6490
bind_addr = 0.0.0.0
token = quoCh8ep
vhost_http_port = 81
```

我查看 frpc 的日志时遇到了问题
![1](https://user-images.githubusercontent.com/75228348/169724283-75231510-35e6-4bb7-894b-87491a87fa63.png)

问题感觉主要是 frp 容器的，但是不知道该怎么解决

3. 服务端防火墙是全端口开放的

**Comment by Drun1baby** [comment]
相关问题截图

题目是能够被 docker 建立，但是不能打开

![2](https://user-images.githubusercontent.com/75228348/169724436-e04650e1-f330-4365-9df4-2167fb54953f.png)


![3](https://user-images.githubusercontent.com/75228348/169724454-c5100235-2f78-4b66-828d-24c176d9310f.png)

**Comment by EkiXu** [comment]
根据log应该是题目的local_port配置问题？
请检查题目配置处port设置是否正常
![image](https://user-images.githubusercontent.com/28667324/169740621-157a3193-dfa6-4174-852a-15c439534f1c.png)

**Comment by Drun1baby** [comment]
woc！！！！！！！！！！！解决了，我爱一琦师傅！！！！

**Comment by Drun1baby** [comment]
写了一篇总结的笔记，我爱一琦师傅~！[CTFm搭建笔记](https://drun1baby.github.io/2022/05/21/CTF%E5%B9%B3%E5%8F%B0%E4%B9%8BCTFm%E7%9A%84%E6%90%AD%E5%BB%BA%E8%BF%87%E7%A8%8B/)

**Comment by Drun1baby** [comment]
一琦师傅，Misc 类型的题目需要如何挂附件呢？是需要自己起一个其他的 Web 服务么

**Comment by EkiXu** [comment]
对于静态附件题目来说，Type 处选择Static URL 在 Attachment URL 里填上附件的下载地址即可，题目展示页会提示下载
后续可能考虑做一个统一的文件存储管理，对接cos/oss或是本地文件存储

**Comment by Drun1baby** [comment]
好的，谢谢师傅啦

**Comment by Drun1baby** [comment]
一琦师傅，pwn 的题目可以使用 pwn-docker 部署嘛

**Comment by EkiXu** [comment]
没有了解过pwn-docker 👀
动态靶机题都是一样的 配好镜像 设置好要映射出来的容器端口就行
