### ISSUE TITLE
可以创建动态flag但是提交时判定flag错

### ISSUE THREAD

**Issue by lx39214** [EkiXu/CTFm#5]
师傅好，刚按步骤搭建完您的CTFm平台，
现以成功创建动态容器和生成动态flag，题目也访问正常

目前发现了一个问题，提交题目里面动态生成的flag会被判定flag错误
题目设置页面所填选项如下，flag留空
[![create-challenge.png](https://i.postimg.cc/rsSMXckP/create-challenge.png)](https://postimg.cc/dZtzrbD2)
但是发现提交正确的flag会报错，如下图所示
（flag来自ENV的$FLAG，说明flag生成没问题）
[![wflag.png](https://i.postimg.cc/gJBFCJQs/wflag.png)](https://postimg.cc/XGFzFVVB)
经过排查发现客户端发送的flag服务端正确接收到了，没有问题，
但是在服务端进行判定发送的flag是否与服务端存储的flag一致时，我发现服务端用于判定的flag是”“，即空字符串
（r flag是提交的flag，c flag是用于判定是否正确的答案flag，3 flag是题目容器创建时生成的flag）
[![d2.png](https://i.postimg.cc/zBdb4CqQ/d2.png)](https://postimg.cc/ft9R90t7)
而创建普通不带动态容器的题目时，flag判定没问题
[![d1.png](https://i.postimg.cc/dQNZS8BC/d1.png)](https://postimg.cc/7b7L5JjP)
进一步调试发现是CTFm/backend/challenge/views.py中的一个类ChallengeViewSet的check_flag方法的问题
用于判定flag的代码如下图箭头2所示
[![187201185611066.png](https://i.postimg.cc/cJPJZmvg/360-187201185611066.png)](https://postimg.cc/v1Lyt5Lb)
而上图箭头1所示代码获取的是题目设置处的配置，challenge对象内部如下图所示
[![obj.png](https://i.postimg.cc/nzx6vj5S/obj.png)](https://postimg.cc/7CBs46qS)
综上所述，在判定动态容器的flag前并没有先读取生成的动态flag，以空字符串与用户提交的flag进行比较，故判定flag错误
解决该问题只需在`if challenge.flag == flag:`前加入几行代码获取生成当前容器时创建的flag即可
```python3
         if challenge.flag == "":
                try:
                    container = ControlUtils.get_user_challenge_container(user, challenge)
                    if container != None:
                        challenge.flag = container.flag
                except:
                    pass
```
如下图所示
[![16720328368275.png](https://i.postimg.cc/CMks3rR8/360-16720328368275.png)](https://postimg.cc/Th2bm9q2)
重启ctfm容器后，重新启动题目，提交动态flag判定正确
[![solv.png](https://i.postimg.cc/bJcMHDGS/solv.png)](https://postimg.cc/94bJcfYc)

**Comment by EkiXu** [comment]
这个版本动态flag这个功能还没有实现，下个正式版会一起推出，可以临时采用这种解决方法

**Comment by lx39214** [comment]
好的，感谢大佬的付出
